<?php //app/code/Klevu/HyvaPage/view/frontend/templates/theme-core.phtml ?>
<link rel="preconnect" href="https://js.klevu.com"/>
<link rel="preconnect" href="https://eucs31v2.ksearchnet.com/"/>
<link rel="preconnect" href="https://visitor.service.ksearchnet.com/"/>

<script crossorigin="anonymous" src_type="url" src="https://js.klevu.com/core/v2/klevu.js"></script>

<script>
    const cs = document.createElement('script')
    cs.src = 'https://js.klevu.com/klevu-js-v1/customizations/klevu-user-customization-16566287474651253311111111111-v2.js';
    cs.type = 'text/javascript';
    document.head.appendChild(cs);
</script>
<script>
    const qs = document.createElement('script')
    qs.src = 'https://js.klevu.com/theme/default/v2/quick-search-theme.js';
    qs.type = 'text/javascript';
    qs.defer = true;
    window.addEventListener('init-external-scripts', () => {
        document.head.appendChild(qs);
    }, {once: true, passive: true});
</script>
